version : "3.9"
services :
  proyectos-balanceo : 
    container_name : proyectos-balanceo
    image : proyectos-balanceo:v1
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=4002    
    build :
      context : .
    ports : 
      - "4003"
    networks : 
      - proyectos-app


  proyectos-balanceo2 : 
    container_name : proyectos-balanceo2
    image : proyectos-balanceo:v1
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=4002    
    ports : 
      - "4003"
    networks : 
      - proyectos-app


  balanceado : 
    container_name : balanceado
    image : balanceado:v1
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=4002     
    build :
      context : ./balanceador
    ports : 
      - "4004:80"
    networks : 
      - proyectos-app


networks : 
  proyectos-app :